using UnityEngine;

public class DiggableGround : MonoBehaviour
{
    public KeyCode digKey = KeyCode.F;
    private bool playerInRange = false;

    private void OnTriggerEnter2D(Collider2D collision)
    {
        if (collision.CompareTag("Player"))
        {
            playerInRange = true;
        }
    }

    private void OnTriggerExit2D(Collider2D collision)
    {
        if (collision.CompareTag("Player"))
        {
            playerInRange = false;
        }
    }

    void Update()
    {
        if (playerInRange && Input.GetKeyDown(digKey))
        {
            Destroy(gameObject);
        }
    }
}
